meta-facebook: santabarbara: use mass write to configure ltc4287
Use ltc4287 mass write address (0x0f) to configure all ltc4287 on the
bus.  Currently, There are two types of PDBs used in the system. The EVB
tray PDB has only one HSC at 0x43, while the compute tray PDB has HSCs
at 0x43 and 0x41. Use mass write address to support both PDB types with
the same AC command.

Change-Id: Ia89419d0ac59c65431b541c8721a08b268df7ef7
Signed-off-by: Fred Chen <Fred.Chen@quantatw.com>

diff --git a/meta-facebook/meta-santabarbara/recipes-phosphor/state/phosphor-state-manager/chassis-powercycle b/meta-facebook/meta-santabarbara/recipes-phosphor/state/phosphor-state-manager/chassis-powercycle
--- a/meta-facebook/meta-santabarbara/recipes-phosphor/state/phosphor-state-manager/chassis-powercycle
+++ b/meta-facebook/meta-santabarbara/recipes-phosphor/state/phosphor-state-manager/chassis-powercycle
@@ -21,13 +21,8 @@ chassis-power-cycle() {
     #       101 18.6 s
     #       110 37.1 s
     #       111 74.2 s
-    if ! i2cset -f -y 47 0x43 0xfd 0x05; then
-        echo "52V HSC1 set reboot delay failed"
-        return 1
-    fi
-
-    if ! i2cset -f -y 47 0x41 0xfd 0x05; then
-        echo "52V HSC2 set reboot delay failed"
+    if ! i2cset -f -y 47 0x0f 0xfd 0x05; then
+        echo "52V HSCs set reboot delay failed"
         return 1
     fi
 
