meta-facebook: yosemite4: Skip invalid GPIO status
Converted check slot presence to a function in the yosemite4-sys-init.
Additionally, updated the logic to skip saving GPIO statuses other
than 0 or 1.

Motivation:
This modification prevents erroneous GPIO statuses from causing the
host-poweron service to misjudge and fail to perform host power on.

Change-Id: Ie13a76902136886dd70f8e9a4f283ba1007131d9
Signed-off-by: Eric Yang <eric.yang.wiwynn@gmail.com>

diff --git a/meta-facebook/meta-yosemite4/recipes-yosemite4/plat-svc/files/yosemite4-early-sys-init b/meta-facebook/meta-yosemite4/recipes-yosemite4/plat-svc/files/yosemite4-early-sys-init
--- a/meta-facebook/meta-yosemite4/recipes-yosemite4/plat-svc/files/yosemite4-early-sys-init
+++ b/meta-facebook/meta-yosemite4/recipes-yosemite4/plat-svc/files/yosemite4-early-sys-init
@@ -51,12 +51,23 @@ set_sd_bic_interface_to_i3c()
 }
 
 # get present status of slot 1~8 and keep in /tmp/gpio/PRSNT_SB_SLOT{1~8}_N
-mkdir -p /tmp/gpio
-for slot in {1..8}
-do
-  get_gpio PRSNT_SB_SLOT"${slot}"_N
-  echo "$?" > /tmp/gpio/PRSNT_SB_SLOT"${slot}"_N
-done
+check_slot_presence() {
+    local ret
+
+    mkdir -p /tmp/gpio
+    for slot in {1..8}
+    do
+        echo "Checking presence status for slot ${slot}..."
+        get_gpio PRSNT_SB_SLOT"${slot}"_N
+        ret=$?
+        if [ "$ret" -eq 0 ] || [ "$ret" -eq 1 ]; then
+            echo "Valid status for slot ${slot}, ret = ${ret}, saving to file..."
+            echo "$ret" > /tmp/gpio/PRSNT_SB_SLOT"${slot}"_N
+        else
+            echo "Invalid status for slot ${slot}, ret = ${ret}, skipping..."
+        fi
+    done
+}
 
 # Function to calculate BIT(n)
 BIT() {
@@ -175,6 +186,8 @@ then
     # adjust the i2c clock duty cycle for bus 11
     devmem 0x1E78A604 32 0x00487006
 fi
+
+check_slot_presence
 
 # Enable all fan input as early as possible
 enable_all_fan_input
