meta-facebook: clemente: Add secondary EROT FPGA RST and 12V control
- Set "BMC_12V_CTRL" to high to enable 12V power for the BMC.
- Set "SEC_EROT_FPGA_RST_L" to high to reset secondary EROT FPGA.

Change-Id: If7acc733648af30db4398c2cc8f842c7fc54597b
Signed-off-by: Leo Wang <leo.jt.wang@fii-foxconn.com>

diff --git a/meta-facebook/meta-catalina/recipes-catalina/plat-svc/files/clemente/standby-power-enable b/meta-facebook/meta-catalina/recipes-catalina/plat-svc/files/clemente/standby-power-enable
--- a/meta-facebook/meta-catalina/recipes-catalina/plat-svc/files/clemente/standby-power-enable
+++ b/meta-facebook/meta-catalina/recipes-catalina/plat-svc/files/clemente/standby-power-enable
@@ -182,6 +182,7 @@ if ! wait_gpio_value "STBY_POWER_PG_3V3" "$GPIO_HIGH" 200 0.1; then
     echo "Error: failed to get STBY_POWER_PG_3V3 as high (1) in 20 sec"
     exit 1
 fi
+set_gpio "BMC_12V_CTRL" "$GPIO_HIGH"
 set_gpio "stby_power_gd_cpld" "$GPIO_HIGH"
 
 bind_i2c_muxes
@@ -190,6 +191,7 @@ bind_gpio_expanders
 
 set_gpio "HMC_PGOOD-O" "$GPIO_HIGH"
 set_gpio "EROT_FPGA_RST_L-O" "$GPIO_HIGH"
+set_gpio "SEC_EROT_FPGA_RST_L" "$GPIO_HIGH"
 set_gpio "HMC_EROT_RST_L-O" "$GPIO_HIGH"
 set_gpio "SCM_HPM_STBY_RST_N" "$GPIO_HIGH"
 
@@ -206,6 +208,11 @@ fi
 
 if ! wait_gpio_value "FPGA_READY_BMC-I" "$GPIO_HIGH" 180 1; then
     echo "Error: failed to get FPGA_READY_BMC-I as high (1) in 180 sec"
+    exit 1
+fi
+
+if ! wait_gpio_value "SEC_FPGA_READY_BMC" "$GPIO_HIGH" 180 1; then
+    echo "Error: failed to get SEC_FPGA_READY_BMC as high (1) in 180 sec"
     exit 1
 fi
 
