meta-facebook: harma: Add NIC MCTP support
Add NIC MCTP support to enable PLDM firmware update.

Change-Id: I81568d404b9d46c8e6d784336d34d34b180ad8a0
Signed-off-by: Daniel Hsu <Daniel-Hsu@quantatw.com>

diff --git a/meta-facebook/meta-harma/recipes-networking/mctp/files/setup-devices-eid b/meta-facebook/meta-harma/recipes-networking/mctp/files/setup-devices-eid
--- a/meta-facebook/meta-harma/recipes-networking/mctp/files/setup-devices-eid
+++ b/meta-facebook/meta-harma/recipes-networking/mctp/files/setup-devices-eid
@@ -1,7 +1,10 @@
 #!/bin/bash
 
 bic_addr=0x20
-busnum=9
+bic_busnum=9
+nic_addr=50
+nic_busnum=1
+nic_eid=90
 maxRetries=10
 
 # Retry a command with optional failover command
@@ -13,7 +16,7 @@ retry_command() {
     local retries=0
 
     while [ "$retries" -lt "$maxRetries" ]; do
-        if bash -c "$command" >/dev/null 2>&1; then
+        if bash -c "$command" 2>&1; then
             return 0
         else
             if [ -n "$failExecuteCmd" ]; then
@@ -31,11 +34,22 @@ retry_command() {
 
 # Learn BIC Endpoint
 learn_endpoint_cmd="busctl call au.com.codeconstruct.MCTP1 \
-    /au/com/codeconstruct/mctp1/interfaces/mctpi2c${busnum} \
+    /au/com/codeconstruct/mctp1/interfaces/mctpi2c${bic_busnum} \
     au.com.codeconstruct.MCTP.BusOwner1 LearnEndpoint ay 1 ${bic_addr}"
 
 if ! retry_command "$learn_endpoint_cmd" "$maxRetries" 1; then
     echo "[Error] Failed to learn BIC EID after $maxRetries attempts."
+    exit 1
+fi
+
+# Set local EID for NIC
+assign_endpoint_cmd="busctl call au.com.codeconstruct.MCTP1 \
+    /au/com/codeconstruct/mctp1/interfaces/mctpi2c${nic_busnum} \
+    au.com.codeconstruct.MCTP.BusOwner1 \
+    AssignEndpointStatic ayy 1 ${nic_addr} ${nic_eid}"
+
+if ! retry_command "$assign_endpoint_cmd" "$maxRetries" 1; then
+    echo "[Error] Failed to assign NIC EID after $maxRetries attempts."
     exit 1
 fi
 
diff --git a/meta-facebook/meta-harma/recipes-networking/mctp/files/setup-local-eid b/meta-facebook/meta-harma/recipes-networking/mctp/files/setup-local-eid
--- a/meta-facebook/meta-harma/recipes-networking/mctp/files/setup-local-eid
+++ b/meta-facebook/meta-harma/recipes-networking/mctp/files/setup-local-eid
@@ -2,9 +2,10 @@
 
 # Set mctpi2c link up and assign local address.
 localEid=8
-busNum=9
 maxRetries=5
 retryInterval=1
+bic_busnum=9
+nic_busnum=1
 
 retry_command() {
 
@@ -25,21 +26,38 @@ retry_command() {
 }
 
 # Retry mctp link command
-if ! retry_command "mctp link set mctpi2c${busNum} up"; then
+if ! retry_command "mctp link set mctpi2c${bic_busnum} up"; then
+    echo "Failed to set mctp link after $maxRetries attempts."
+    exit 1
+fi
+
+if ! retry_command "mctp link set mctpi2c${nic_busnum} up"; then
     echo "Failed to set mctp link after $maxRetries attempts."
     exit 1
 fi
 
 # Check if local EID is already set
 mctpOutput=$(mctp address show)
-if echo "$mctpOutput" | grep -q "mctpi2c${busNum}"; then
-    echo "mctpi2c${busNum} local EID already set"
+
+if echo "$mctpOutput" | grep -q "mctpi2c${bic_busnum}"; then
+    echo "mctpi2c${bic_busnum} local EID already set"
 else
     # Retry mctp addr add command
-    if ! retry_command "mctp addr add ${localEid} dev mctpi2c${busNum}"; then
+    if ! retry_command "mctp addr add ${localEid} dev mctpi2c${bic_busnum}"; then
         echo "Failed to add mctp address after $maxRetries attempts."
         exit 1
     fi
 fi
-echo "mctpi2c${busNum} local EID set to ${localEid}"
+echo "mctpi2c${bic_busnum} local EID set to ${localEid}"
+
+if echo "$mctpOutput" | grep -q "mctpi2c${nic_busnum}"; then
+    echo "mctpi2c${nic_busnum} local EID already set"
+else
+    # Retry mctp addr add command
+    if ! retry_command "mctp addr add ${localEid} dev mctpi2c${nic_busnum}"; then
+        echo "Failed to add mctp address after $maxRetries attempts."
+        exit 1
+    fi
+fi
+echo "mctpi2c${nic_busnum} local EID set to ${localEid}"
 exit 0
