meta-facebook: harma: setting bic mtu to 100
Setting the MCTP MTU between Harma and Aegis Bic to 100
because there is a bug in Linux MCTP-I2C when reassembling packets.
So, temporarily increasing the MTU to 100 as a workaround.

Testing:
Mar 24 19:00:03 bmc setup-bic-eid[6976]: yisb 10 1 "/au/com/
    codeconstruct/mctp1/networks/1/endpoints/10" true
Mar 24 19:00:03 bmc setup-bic-eid[6975]: BIC EID set to 0x20
Mar 24 19:00:03 bmc setup-bic-eid[6975]: BIC MTU set to 100
Mar 24 19:00:03 bmc systemd[1]: Started MCTP control protocol daemon.

Change-Id: Id6460d463f3f481c530acfc446c1511c0c4334b6
Signed-off-by: Daniel Hsu <Daniel-Hsu@quantatw.com>

diff --git a/meta-facebook/meta-harma/recipes-networking/mctp/files/setup-bic-eid b/meta-facebook/meta-harma/recipes-networking/mctp/files/setup-bic-eid
--- a/meta-facebook/meta-harma/recipes-networking/mctp/files/setup-bic-eid
+++ b/meta-facebook/meta-harma/recipes-networking/mctp/files/setup-bic-eid
@@ -2,6 +2,7 @@
 
 # Set BIC EID
 bic_addr=0x20
+bic_eid=10
 busnum=9
 maxRetries=10
 retryInterval=1
@@ -32,8 +33,20 @@ command="
     ay 1 ${bic_addr}"
 
 if ! retry_command "$command"; then
-    echo "Failed to busctl call after $maxRetries attempts."
+    echo "Failed to learn BIC EID after $maxRetries attempts."
     exit 1
 fi
 echo "BIC EID set to ${bic_addr}"
+
+command="
+    busctl call au.com.codeconstruct.MCTP1 \
+    /au/com/codeconstruct/mctp1/networks/1/endpoints/${bic_eid} \
+    au.com.codeconstruct.MCTP.Endpoint1 SetMTU u 100"
+
+if ! retry_command "$command"; then
+    echo "Failed to set BIC MTU after $maxRetries attempts."
+    exit 1
+fi
+echo "BIC MTU set to 100"
+
 exit 0
