meta-facebook: harma: remove SetMtu
Observed recurring pldmTransport::sendMsg failures with response code
errno 113 - ECONNABORTED, likely due to a broken MCTP socket or a
dead endpoint. It seems to depend on busctrl to set the MTU value.
Maybe setting the MTU takes more time to initialize.

Setting the MTU was a workaround to avoid encountering a kernel issue.
Currently, this kernel issue has been fixed, so we can remove the
workaround.

'''
https://github.com/torvalds/linux/commit/70facbf978ac90c6da17a3de2a8dd111b06f1bac
'''

Change-Id: Id6ae37202ff3cd974f8fcda43353831da38cb714
Signed-off-by: Peter Yin <peter.yin@quantatw.com>

diff --git a/meta-facebook/meta-harma/recipes-networking/mctp/files/setup-bic-eid b/meta-facebook/meta-harma/recipes-networking/mctp/files/setup-bic-eid
--- a/meta-facebook/meta-harma/recipes-networking/mctp/files/setup-bic-eid
+++ b/meta-facebook/meta-harma/recipes-networking/mctp/files/setup-bic-eid
@@ -1,52 +1,42 @@
 #!/bin/bash
 
-# Set BIC EID
 bic_addr=0x20
-bic_eid=10
 busnum=9
 maxRetries=10
-retryInterval=1
 
+# Retry a command with optional failover command
 retry_command() {
+    local command="$1"
+    local maxRetries=${2:-10}
+    local retryInterval=${3:-1}
+    local failExecuteCmd=${4:-""}
+    local retries=0
 
-    command="$1"
-    retries=0
-
-    while [ $retries -lt $maxRetries ]; do
-        if bash -c "$command"; then
+    while [ "$retries" -lt "$maxRetries" ]; do
+        if bash -c "$command" >/dev/null 2>&1; then
             return 0
         else
+            if [ -n "$failExecuteCmd" ]; then
+                bash -c "$failExecuteCmd"
+            fi
+
             retries=$((retries + 1))
-            echo "Retry $retries/$maxRetries: Command failed. Retrying in $retryInterval seconds..."
-            sleep $retryInterval
+            sleep "$retryInterval"
         fi
     done
 
+    echo "[Error] Command failed after $maxRetries retries." >&2
     return 1
 }
 
-command="
-    busctl call au.com.codeconstruct.MCTP1 \
+# Learn BIC Endpoint
+learn_endpoint_cmd="busctl call au.com.codeconstruct.MCTP1 \
     /au/com/codeconstruct/mctp1/interfaces/mctpi2c${busnum} \
-    au.com.codeconstruct.MCTP.BusOwner1 \
-    LearnEndpoint \
-    ay 1 ${bic_addr}"
+    au.com.codeconstruct.MCTP.BusOwner1 LearnEndpoint ay 1 ${bic_addr}"
 
-if ! retry_command "$command"; then
-    echo "Failed to learn BIC EID after $maxRetries attempts."
+if ! retry_command "$learn_endpoint_cmd" "$maxRetries" 1; then
+    echo "[Error] Failed to learn BIC EID after $maxRetries attempts."
     exit 1
 fi
-echo "BIC EID set to ${bic_addr}"
-
-command="
-    busctl call au.com.codeconstruct.MCTP1 \
-    /au/com/codeconstruct/mctp1/networks/1/endpoints/${bic_eid} \
-    au.com.codeconstruct.MCTP.Endpoint1 SetMTU u 100"
-
-if ! retry_command "$command"; then
-    echo "Failed to set BIC MTU after $maxRetries attempts."
-    exit 1
-fi
-echo "BIC MTU set to 100"
 
 exit 0
