meta-facebook: yosemite4: set powerstate for empty slots
The power state of empty slot is not handled correctly due to
obmc-chassis-poweron@{}.target keeping active.

1. Get present pins of slots in yosemite4-early-sys-init.
2. Add a judgement in power control scripts to return fail when slot is
not present.
3. Add service to handle power control failure.

Tested:
1. Get power state while Yv4 being powered on with some empty slots, the
power state of empty slots should be off - pass.

Change-Id: I3b8c10bb12d6e54cbe89834962e52039bb497c83
Signed-off-by: Bright Cheng <bright.cheng.wiwynn@gmail.com>

diff --git a/meta-facebook/meta-yosemite4/recipes-yosemite4/plat-tool/files/yosemite4-common-functions b/meta-facebook/meta-yosemite4/recipes-yosemite4/plat-tool/files/yosemite4-common-functions
--- a/meta-facebook/meta-yosemite4/recipes-yosemite4/plat-tool/files/yosemite4-common-functions
+++ b/meta-facebook/meta-yosemite4/recipes-yosemite4/plat-tool/files/yosemite4-common-functions
@@ -20,6 +20,26 @@ set_gpio()
     return 0
 }
 
+get_gpio()
+{
+    local NET_NAME=$1
+    local ret=2
+    mapfile -t -d " " GPIO_INFO < <(gpiofind "$NET_NAME")
+    if [ "${#GPIO_INFO[@]}" -ne 2 ]; then
+        echo "get_gpio: can not find gpio, $NET_NAME"
+        return 2
+    fi
+
+    echo -n "get_gpio: get $NET_NAME"
+    if ! ret=$(gpioget "${GPIO_INFO[0]}" "${GPIO_INFO[1]%$'\n'}"); then
+        echo " failed"
+        return 2
+    fi
+
+    echo " success"
+    return "${ret}"
+}
+
 check_nuvoton_board()
 {
     set +e
