meta-facebook: yosemite4: modify service window
Service window changes fan duty to 90% when a slot is unplugged.
Currently, it uses the virtual sensor
SENTINEL_DOME_SLOT_PRESENT_PERCENTAGE to monitor each slot's
MB_FIO_TEMP sensor to detect slot removal.
However, this triggers the service window during slot AC off.

Therefore, change implementation to modify
SENTINEL_DOME_SLOT_PRESENT_PERCENTAGE value when GPIO monitors slot
PRSNT PIN changes.

- Test Plan:
Build code - pass
Fan speed does not change to 90% during one slot AC off - pass
Fan duty changes to 90% after slot is unplugged - pass

Change-Id: I294d041ee8b66916b021327ee6f616793eedd034
Signed-off-by: Eric Yang <eric.yang.wiwynn@gmail.com>

diff --git a/meta-facebook/meta-yosemite4/recipes-yosemite4/plat-tool/files/yosemite4-common-functions b/meta-facebook/meta-yosemite4/recipes-yosemite4/plat-tool/files/yosemite4-common-functions
--- a/meta-facebook/meta-yosemite4/recipes-yosemite4/plat-tool/files/yosemite4-common-functions
+++ b/meta-facebook/meta-yosemite4/recipes-yosemite4/plat-tool/files/yosemite4-common-functions
@@ -54,3 +54,40 @@ get_product_version()
     PRODUCT_VERSION=$(busctl get-property xyz.openbmc_project.EntityManager /xyz/openbmc_project/inventory/system/board/Yosemite_4_"$FRU_NAME" xyz.openbmc_project.Inventory.Decorator.Revision Version| awk -F\" '{print $2}')
     echo "$PRODUCT_VERSION"
 }
+
+set_sentinel_dome_slot_present_percentage()
+{
+    local sentinel_dome_slot_present_percentage="$1"
+
+    if ! busctl set-property "xyz.openbmc_project.VirtualSensor" \
+            "/xyz/openbmc_project/sensors/utilization/SENTINEL_DOME_SLOT_PRESENT_PERCENTAGE" \
+            "xyz.openbmc_project.Sensor.Value" Value d "$sentinel_dome_slot_present_percentage" 2>&1; then
+        echo "Failed to set SENTINEL_DOME_SLOT_PRESENT_PERCENTAGE to ${sentinel_dome_slot_present_percentage}%."
+        return 1
+    else
+        echo "Successfully set SENTINEL_DOME_SLOT_PRESENT_PERCENTAGE to ${sentinel_dome_slot_present_percentage}%."
+        return 0
+    fi
+}
+
+handle_service_window()
+{
+    local value=0
+    local present_count=0
+    local sentinel_dome_slot_present_percentage
+
+    for i in {1..8}; do
+        value=$(cat /tmp/gpio/PRSNT_SB_SLOT"${i}"_N)
+        if [ "$value" -eq 0 ]; then
+            present_count=$((present_count + 1))
+        fi
+    done
+
+    echo "Slot present count: ${present_count}"
+    sentinel_dome_slot_present_percentage=$(awk "BEGIN {printf \"%.1f\", $present_count * 12.5}")
+    if ! set_sentinel_dome_slot_present_percentage "$sentinel_dome_slot_present_percentage"; then
+        return 1
+    else
+        return 0
+    fi
+}
