meta-facebook: ventura: Add checked for the DUID-LL configuration
The root cause is that during BMC boot, the Entity Manager has not yet
written the MAC address to the Inventory when the Network service start.
This results in the error “Exception occurred during getting of MAC
address from Inventory” and triggers a restart of the Network service.

However, the file 00-bmc-eth0.network is already reconfigured with the
DUID-LL settings during the first Network service start. When the Network
service restart, the file is overwritten and ends up without the DUID-LL
settings, which ultimately leads to the DHCPv6 failure.

Therefore, we added an extended check function for the DUID-LL settings
to ensure that after the Network service restart, the 00-bmc-eth0.network
file is also checked for the presence of the DUID-LL configuration.

Change-Id: I4c96ee6bd5abed9d40c462f53b512893be338826
Signed-off-by: Jason Hsu <Jason-Hsu@quantatw.com>

diff --git a/meta-facebook/recipes-fb/reconfig-interface-duid-ll/reconfig-interface-duid-ll/reconfig-interface-duid-ll b/meta-facebook/recipes-fb/reconfig-interface-duid-ll/reconfig-interface-duid-ll/reconfig-interface-duid-ll
--- a/meta-facebook/recipes-fb/reconfig-interface-duid-ll/reconfig-interface-duid-ll/reconfig-interface-duid-ll
+++ b/meta-facebook/recipes-fb/reconfig-interface-duid-ll/reconfig-interface-duid-ll/reconfig-interface-duid-ll
@@ -4,23 +4,28 @@ INTF_NAME="$1"
 NET_CONFIG_FILE="/etc/systemd/network/00-bmc-${INTF_NAME}.network"
 DHCPv6_SETTING_ADD="ClientIdentifier=duid\nIAID=0\nDUIDType=link-layer"
 
-for i in {1..10}; do
-    if [ -f "$NET_CONFIG_FILE" ]; then
-        if ! grep -q "^DUIDType=" "$NET_CONFIG_FILE"; then
-            sed -i "/^\[DHCPv6\]/a $DHCPv6_SETTING_ADD" "$NET_CONFIG_FILE"
-            echo "Added LL settings to network configuration file."
-            echo "Restarting systemd-networkd service..."
-            systemctl restart systemd-networkd.service
-            exit 0
+# retry: wait for network manager to finish writing DHCPv6 section
+for round in {1..3}; do
+    for i in {1..10}; do
+        if [ -f "$NET_CONFIG_FILE" ]; then
+            if ! grep -q "^DUIDType=" "$NET_CONFIG_FILE"; then
+                sed -i "/^\[DHCPv6\]/a $DHCPv6_SETTING_ADD" "$NET_CONFIG_FILE"
+                echo "Added LL settings to network configuration file."
+                echo "Restarting systemd-networkd service..."
+                systemctl restart systemd-networkd.service
+                break
+            else
+                echo "'DUIDType' already exists in $NET_CONFIG_FILE. Exiting..."
+                break
+            fi
         else
-            echo "'DUIDType' already exists in $NET_CONFIG_FILE. Exiting..."
-            exit 0
+            echo "File $NET_CONFIG_FILE not present. Retrying... ($i/10)"
         fi
-    else
-        echo "File $NET_CONFIG_FILE not present. Retrying... ($i/10)"
-    fi
-    sleep 5
+        sleep 5
+    done
+    echo "Waiting for DHCPv6 section... ($round/3)"
+    sleep 25
 done
 
-echo "Failed to update $NET_CONFIG_FILE after 10 attempts."
+echo "Check $NET_CONFIG_FILE after 3 rounds."
 exit 1
