meta-facebook: ventura: re-implementing front LED amber function
After removing the phosphor-gpio-monitor leak detector configuration
and moving it to the EM configuration. The front panel LED amber
functionality during a leak event was lost. We are now re-implementing
this functionality through the D-Bus sensors service.

Change-Id: I63c719123fade6d9b61e3316ecacbc271641fd7b
Signed-off-by: Jason Hsu <Jason-Hsu@quantatw.com>

diff --git a/meta-facebook/meta-ventura/recipes-phosphor/sensors/dbus-sensors/critical-leak-handler b/meta-facebook/meta-ventura/recipes-phosphor/sensors/dbus-sensors/critical-leak-handler
--- a/meta-facebook/meta-ventura/recipes-phosphor/sensors/dbus-sensors/critical-leak-handler
+++ b/meta-facebook/meta-ventura/recipes-phosphor/sensors/dbus-sensors/critical-leak-handler
@@ -5,26 +5,56 @@ if [ $# -ne 1 ]; then
     exit 1
 fi
 
-SUPPORTED_LEAK=0
+EnableLeds()
+{
+    local portnum=$1
 
-RACK_LEAKS=(
-    "RackDripPan"
-    "RackFloorLeak1"
-    "RackFloorLeak2"
-    "RackRightManifold"
-    "RackLeftManifold"
-)
-for RACK_LEAK in "${RACK_LEAKS[@]}"; do
-    if [[ "$1" == "$RACK_LEAK" ]]; then
-        SUPPORTED_LEAK=1
-        break
-    fi
-done
+    busctl set-property "xyz.openbmc_project.LED.GroupManager" \
+        "/xyz/openbmc_project/led/groups/leakport""$portnum""_amber" \
+        "xyz.openbmc_project.Led.Group" "Asserted" "b" "true"
 
-if [ $SUPPORTED_LEAK -eq 0 ]; then
-    echo "Leak handling not supported for $1"
-    exit 0
+    busctl set-property "xyz.openbmc_project.LED.GroupManager" \
+        "/xyz/openbmc_project/led/groups/leakport""$portnum""_blue" \
+        "xyz.openbmc_project.Led.Group" "Asserted" "b" "false"
+}
+
+DetectorName=$1
+
+LeakType=$(echo "$DetectorName" | cut -d'_' -f2)
+temp=${DetectorName#*Port}
+portnum=${temp%%_*}
+
+if [ "$LeakType" == "Big" ]; then
+  EnableLeds "${portnum}"
 fi
+
+if [[ "$DetectorName" == "RackDripPan" || "$DetectorName" == "RackRightManifold" || "$DetectorName" == "RackLeftManifold" ]]; then
+
+PSU_Off ()
+{
+    curl -f -s -o /dev/null \
+    --cacert /var/facebook/rootcanal/rc_digicert_ca.pem \
+    --cert /mnt/data/etc/x509_highpriv_host.cert \
+    --key /mnt/data/etc/x509_highpriv_host.key \
+    -X POST "https://${RACKPOWER_HOSTNAME}/${RACKPOWER_URI}" \
+    --data '{"ResetType": "ForceOff"}' \
+    --resolve "${RACKPOWER_HOSTNAME}:443:${RACKPOWER_IP}"
+
+    CMD_STATUS=$?
+
+    if [ $CMD_STATUS -eq 0 ]; then
+        echo "Rack Power Off command sent successfully."
+        busctl call xyz.openbmc_project.Logging /xyz/openbmc_project/logging \
+            xyz.openbmc_project.Logging.Create Create "ssa{ss}" "Successfully sent rack power off command during rack leak to RackSwitch" \
+            xyz.openbmc_project.Logging.Entry.Level.Error 2 "DetectorName" "$1" "RackSwitch" "$RACKPOWER_HOSTNAME"
+    else
+        echo "Error: Failed($CMD_STATUS) to send Rack Power Off command."
+        busctl call xyz.openbmc_project.Logging /xyz/openbmc_project/logging \
+            xyz.openbmc_project.Logging.Create Create "ssa{ss}" "Failed to send rack power off command during rack leak to RackSwitch" \
+            xyz.openbmc_project.Logging.Entry.Level.Error 3 "DetectorName" "$1" "RackSwitch" "$RACKPOWER_HOSTNAME" "Error" 	"$CMD_STATUS"
+        exit 1
+    fi
+}
 
 files=(
     "/var/facebook/rootcanal/rc_digicert_ca.pem"
@@ -46,33 +76,6 @@ RACKPOWER_HOSTNAME=$(cat /mnt/data/etc/rackpower_hostname)
 RACKPOWER_IP=$(cat /mnt/data/etc/rackpower_ipaddr)
 RACKPOWER_URI="redfish/v1/Chassis/Rack/Actions/Chassis.Reset"
 
-curl -f -s -o /dev/null \
-    --cacert /var/facebook/rootcanal/rc_digicert_ca.pem \
-    --cert /mnt/data/etc/x509_highpriv_host.cert \
-    --key /mnt/data/etc/x509_highpriv_host.key \
-    -X POST "https://${RACKPOWER_HOSTNAME}/${RACKPOWER_URI}" \
-    --data '{"ResetType": "ForceOff"}' \
-    --resolve "${RACKPOWER_HOSTNAME}:443:${RACKPOWER_IP}"
+PSU_Off "$1"
 
-CMD_STATUS=$?
-
-if [ $CMD_STATUS -eq 0 ]; then
-    echo "Rack Power Off command sent successfully."
-
-    busctl call xyz.openbmc_project.Logging /xyz/openbmc_project/logging \
-        xyz.openbmc_project.Logging.Create Create "ssa{ss}" \
-        "Successfully sent rack power off command during rack leak to RackSwitch" \
-        xyz.openbmc_project.Logging.Entry.Level.Error 2 "DetectorName" "$1" \
-        "RackSwitch" "$RACKPOWER_HOSTNAME"
-
-else
-    echo "Error: Failed($CMD_STATUS) to send Rack Power Off command."
-
-    busctl call xyz.openbmc_project.Logging /xyz/openbmc_project/logging \
-        xyz.openbmc_project.Logging.Create Create "ssa{ss}" \
-        "Failed to send rack power off command during rack leak to RackSwitch" \
-        xyz.openbmc_project.Logging.Entry.Level.Error 3 "DetectorName" "$1" \
-        "RackSwitch" "$RACKPOWER_HOSTNAME" "Error" "$CMD_STATUS"
-
-    exit 1
 fi
