meta-facebook: clemente: fix standby-AC cycle to follow power sequence
Summary:
The current standby-AC power cycling process is not optimal. If the HSC
power is turned off while the host power is up, then the FPGA would see
this as a power fault. There is a small window of time where the FPGA
remains functional from holdup capacitance in which it will assert power
brake and perform power down sequence before it loses energy. It is
expected(and required) that during a power fault event the FPGA will
assert power brake. So if an AC cycle is performed in this way then it's
expected that this power brake could occurs. The NVIDIA BMC ac cycle
process will first do a force shutdown before cutting standby power.

To address this, we have improved the standby-AC power
cycling process as follows:

1. Based on NVIDIA's recommended AC power-down sequence, the host is
forcibly powered off before turning off the HSC power.
2. Fix original standby-AC power cycling process, enabling power cycling
by simply controlling the Bianca IO Expander BMC_STBY_CYCLE-O pin.

verified:
1. set "hard_shutdown_host" gpio to 0, and check host power is turn off
from mfg-tool power-state.
2. start standby-AC power cycling after set "BMC_STBY_CYCLE-O"
gpio to 1.

Change-Id: Ia3405ae814f80c17b3b11a5dea7bf4f80ca47a12
Signed-off-by: Kimi Chen <kimi.zy.chen@fii-foxconn.com>

diff --git a/meta-facebook/meta-catalina/recipes-phosphor/state/phosphor-state-manager/clemente/power-cmd b/meta-facebook/meta-catalina/recipes-phosphor/state/phosphor-state-manager/clemente/power-cmd
--- a/meta-facebook/meta-catalina/recipes-phosphor/state/phosphor-state-manager/clemente/power-cmd
+++ b/meta-facebook/meta-catalina/recipes-phosphor/state/phosphor-state-manager/clemente/power-cmd
@@ -65,14 +65,20 @@ chassis_power_cycle_button()
 
 chassis_power_cycle()
 {
+    # Following the recommended AC power down sequence:
+    # Force shutdown of the host before cutting the HSC power.
+    # If turn HSC power off while main power is up (and not doing a proper shutdown
+    # before removing standby power), then the FPGA would see this as a power fault.
+    if [ "$(host_power_status)" == "on" ]; then
+        set_gpio "hard_shutdown_host" 0
+        if ! wait_host_power_change "off" 5; then
+            echo "[DEBUG] force-off host failed in power cycle"
+        fi
+    fi
     # There are HSCs(LM5066i) on the PDB board, and BMC configure the HPM board's Bianca IO Expander
     # then it starts standby-AC power cycling for the tray.
     # This behavior equal i2ctransfer -f -y 2 w2@0x20 0x06 0xd7 from NV.
-
-    set_gpio "HMC_PGOOD-O" 1
-    sleep 0.1
     set_gpio "BMC_STBY_CYCLE-O" 1
-
     return 0
 }
 
