meta-facebook: santabarbara: Update SIT V3 CPLD register address after hardware change
Due to a hardware update that modified the CPLD register mapping, the
SIT V3 register address is updated from 0x21 to 0x51 to match the new
hardware design.

Test on santabarbara platform with on sitv3 board on bus 8
```
Jan 22 00:19:36 bmc Santabarbara Eid Init[352]: Slot 13: No device found, skipping initia…tion
Jan 22 00:19:36 bmc Santabarbara Eid Init[352]: Slot 10: No device found, skipping initia…tion
Jan 22 00:19:57 bmc Santabarbara Eid Init[352]: Slot 8: Verifying SITv3 register 0x50
Jan 22 00:19:57 bmc Santabarbara Eid Init[352]: Slot 8: Read data: 0x02 0x1e, matches exp…SSED
Jan 22 00:19:57 bmc Santabarbara Eid Init[352]: Slot 6: No device found, skipping check
Jan 22 00:19:57 bmc Santabarbara Eid Init[352]: Slot 13: No device found, skipping check
Jan 22 00:19:57 bmc Santabarbara Eid Init[352]: Slot 10: No device found, skipping check
Jan 22 00:19:57 bmc Santabarbara Eid Init[352]: I3C hotjoin enabled
Jan 22 00:19:57 bmc systemd[1]: santabarbara-eid-init.service: Deactivated successfully.
Jan 22 00:19:57 bmc systemd[1]: Finished Set I2C EID at boot.
Hint: Some lines were ellipsized, use -l to show in full.
```

Test on santabarbara platform with four rainbow board
```
Jan 22 01:20:56 bmc Santabarbara Eid Init[423]: Slot 13 setup success
Jan 22 01:20:57 bmc Santabarbara Eid Init[423]: Slot 10: Detecting Rainbow card, add the …0x50
Jan 22 01:20:57 bmc Santabarbara Eid Init[423]: Slot 10 setup success
Jan 22 01:21:18 bmc Santabarbara Eid Init[423]: Slot 8: Rainbow reboot check finished
Jan 22 01:21:19 bmc Santabarbara Eid Init[423]: Slot 6: Rainbow reboot check finished
Jan 22 01:21:19 bmc Santabarbara Eid Init[423]: Slot 13: Rainbow reboot check finished
Jan 22 01:21:19 bmc Santabarbara Eid Init[423]: Slot 10: Rainbow reboot check finished
Jan 22 01:21:19 bmc Santabarbara Eid Init[423]: I3C hotjoin enabled
Jan 22 01:21:19 bmc systemd[1]: santabarbara-eid-init.service: Deactivated successfully.
Jan 22 01:21:19 bmc systemd[1]: Finished Set I2C EID at boot.
```

Change-Id: If6b3049c783c8aaee54e88010a5bae1e92f7d9aa
Signed-off-by: Henry Wu <Henry_Wu@quantatw.com>

diff --git a/meta-facebook/meta-santabarbara/recipes-santabarbara/plat-svc/files/santabarbara-eid-init b/meta-facebook/meta-santabarbara/recipes-santabarbara/plat-svc/files/santabarbara-eid-init
--- a/meta-facebook/meta-santabarbara/recipes-santabarbara/plat-svc/files/santabarbara-eid-init
+++ b/meta-facebook/meta-santabarbara/recipes-santabarbara/plat-svc/files/santabarbara-eid-init
@@ -58,9 +58,9 @@ main() {
             i2cset -y "$slot" 0x21 1 0
             i2cset -y "$slot" 0x21 1 1
 
-       elif i2cdetect -y "$slot" | grep -Eq "^20:([[:space:]]+..){1}[[:space:]]+(UU|[0-9a-f]{2})"; then
-            echo "Slot $slot: Detecting SITv3 card, set the $sitv3_val at 0x21"
-            cmd="i2cset -y $slot 0x21 $sitv3_val"
+       elif i2cdetect -y "$slot" | grep -Eq "^50:([[:space:]]+..){1}[[:space:]]+(UU|[0-9a-f]{2})"; then
+            echo "Slot $slot: Detecting SITv3 card, set the $sitv3_val at 0x51"
+            cmd="i2cset -y $slot 0x51 $sitv3_val"
             if retry_i2c_command "$cmd" "$slot" "bus setup"; then
                 echo "Slot $slot setup success"
             else
@@ -79,9 +79,9 @@ main() {
 
         if i2cdetect -y "$slot" | grep -Eq '^50:[[:space:]]+(UU|[0-9a-f]{2})'; then
             echo "Slot $slot: Rainbow reboot check finished"
-        elif i2cdetect -y "$slot" | grep -Eq '^20:([[:space:]]+..){1}[[:space:]]+(UU|[0-9a-f]{2})'; then
+        elif i2cdetect -y "$slot" | grep -Eq '^50:([[:space:]]+..){1}[[:space:]]+(UU|[0-9a-f]{2})'; then
             echo "Slot $slot: Verifying SITv3 register 0x50"
-            res=$(i2ctransfer -y "$slot" w1@0x21 0x50 r2 2>/dev/null || echo "FAIL")
+            res=$(i2ctransfer -y "$slot" w1@0x51 0x50 r2 2>/dev/null || echo "FAIL")
             if [[ "$res" == "FAIL" ]]; then
                 echo "ERROR: i2ctransfer failed on slot $slot"
             else
