meta-facebook: yosemite5: Modify the power control process
Change acpi to graceful and runtime to force according to RTP
requirements

Change-Id: I160ffda77681181f3e59b99d6cb29bfac7d25f05
Signed-off-by: Leo Yang <Leo-Yang@quantatw.com>

diff --git a/meta-facebook/meta-yosemite5/recipes-phosphor/state/phosphor-state-manager/host-graceful-poweroff b/meta-facebook/meta-yosemite5/recipes-phosphor/state/phosphor-state-manager/host-graceful-poweroff
--- a/meta-facebook/meta-yosemite5/recipes-phosphor/state/phosphor-state-manager/host-graceful-poweroff
+++ b/meta-facebook/meta-yosemite5/recipes-phosphor/state/phosphor-state-manager/host-graceful-poweroff
@@ -6,4 +6,7 @@ source /usr/libexec/phosphor-state-manager/power-cmd
 # DC off
 echo "Starting Graceful Power off"
 
-graceful_power_off
+if ! graceful_power_off; then
+    echo "Graceful Power off failed."
+    exit 1
+fi
