meta-facebook: harma: Add host off delay when bios update
The latest power-off time is 48 seconds due to the implementation
of the AMD force-off issue. Thus, we need to add a delay in the BIOS
update script. This commit adds a for loop to check the power-off
status every second, which enhances the update procedure.

Change-Id: I179b861e63a65dd6b9a509dd7fb4e7ad1ea72cec
Signed-off-by: Peter Yin <peter.yin@quantatw.com>

diff --git a/meta-facebook/meta-harma/recipes-phosphor/flash/phosphor-software-manager/bios-update b/meta-facebook/meta-harma/recipes-phosphor/flash/phosphor-software-manager/bios-update
--- a/meta-facebook/meta-harma/recipes-phosphor/flash/phosphor-software-manager/bios-update
+++ b/meta-facebook/meta-harma/recipes-phosphor/flash/phosphor-software-manager/bios-update
@@ -35,13 +35,20 @@ echo "Bios upgrade started at $(date)"
 echo "Power off host server"
 obmcutil poweroff
 
-sleep 25
-if [ "$(power_status)" != "off" ];
-then
-    echo "Host server didn't power off"
-    echo "Bios upgrade failed"
-    exit 1
-fi
+for i in $(seq 1 60)
+do
+    sleep 1
+    if [ "$(power_status)" == "off" ]; then
+        break
+    fi
+
+    if [ "$i" -eq 60 ]; then
+        echo "Host server didn't power off"
+        echo "Bios upgrade failed"
+        exit 1
+    fi
+done
+
 echo "Host server powered off"
 
 #Flip GPIO to access SPI flash used by host.
