meta-facebook: catalina: Add second FPGA ready check
This commit introduces a second FPGA ready check to align with NVIDIA's
reference code. By ensuring that both FPGA ready pins are asserted
before proceeding, this additional check helps prevent unexpected
behavior and enhances system stability.

Change-Id: I65f23841fe0890c672da42f4d8a5796eb5f76d17
Signed-off-by: Potin Lai <potin.lai@quantatw.com>

diff --git a/meta-facebook/meta-catalina/recipes-catalina/plat-svc/files/standby-power-enable b/meta-facebook/meta-catalina/recipes-catalina/plat-svc/files/standby-power-enable
--- a/meta-facebook/meta-catalina/recipes-catalina/plat-svc/files/standby-power-enable
+++ b/meta-facebook/meta-catalina/recipes-catalina/plat-svc/files/standby-power-enable
@@ -183,6 +183,11 @@ if ! wait_gpio_value "FPGA_READY_BMC" "$GPIO_HIGH" 180 1; then
     exit 1
 fi
 
+if ! wait_gpio_value "SEC_FPGA_READY_BMC" "$GPIO_HIGH" 180 1; then
+    echo "Error: failed to get SEC_FPGA_READY_BMC as high (1) in 180 sec"
+    exit 1
+fi
+
 bind_fru_eeproms
 set_bmc_ready
 
