meta-facebook: yosemite4: Support wait mechanism
Add a wait mechanism to check whether WF BIC is coming up or not.
If WF BIC is not coming up with 60s, then call dbus method
to set EID for WF BIC.

Test plan:
Build Code - pass

Change-Id: I406e662da65dae09fcb220ea3149a7e3914f2b51
Signed-off-by: Eric Yang <eric.yang.wiwynn@gmail.com>

diff --git a/meta-facebook/meta-yosemite4/recipes-phosphor/gpio/phosphor-gpio-monitor/rescan-wf-bic b/meta-facebook/meta-yosemite4/recipes-phosphor/gpio/phosphor-gpio-monitor/rescan-wf-bic
--- a/meta-facebook/meta-yosemite4/recipes-phosphor/gpio/phosphor-gpio-monitor/rescan-wf-bic
+++ b/meta-facebook/meta-yosemite4/recipes-phosphor/gpio/phosphor-gpio-monitor/rescan-wf-bic
@@ -2,16 +2,35 @@
 
 sd_eid=$(($1 * 10))
 wf_eid=$(($1 * 10 + 2))
+count=0
 
-# It takes about 6 seconds for setting up MCTP endpoint after slot plugged-in
+# We found one corner case is that if the rescan-wf-bic script checks a WF
+# slot and not probe MCTP EID yet, and then go to the workaround to probe
+# MCTP EID again. In this case we found that MCTP EID was already probed
+# successfully before going to the workaround. But at this moment we saw
+# MCTP response timeout for EID e.g. 72 (WF-7) occurred and it caused mctpd
+# to remove this EID 72 due to this timeout and then PLDM sensor missing happened.
+
+# To avoid this issue, a 10-second delay is not enough when the BMC is busy
+# handling the power cycle for all 8 slots.
+# Instead, increase the delay to 30 seconds as a solution.
 sleep 30
+
+# This method of probing the Wf EID through SetupEndpointByConfigPath
+# should ensure that it only executes if the Wf EID has truly not been probed.
 # Check if we got WF BIC's EID
-busctl get-property xyz.openbmc_project.MCTP /xyz/openbmc_project/mctp/1/"$wf_eid" xyz.openbmc_project.MCTP.Endpoint EID
-status=$?
-if [ $status -eq 0 ]; then
-    echo "WF BIC's EID $wf_eid found successfully"
-    exit 0
-fi
+while [ $count -lt 12 ]; do
+    busctl get-property xyz.openbmc_project.MCTP /xyz/openbmc_project/mctp/1/"$wf_eid" xyz.openbmc_project.MCTP.Endpoint EID
+    isMctpConnect=$?;
+    echo $isMctpConnect
+    if [ $isMctpConnect -eq 0 ]; then
+        echo "WF BIC's EID $wf_eid found successfully"
+        exit 0;
+    fi
+    echo "WF BIC's EID $wf_eid not found yet."
+    sleep 5;
+    count=$((count + 1))
+done
 
 count=0
 while [ $count -lt 3 ]; do
