meta-google: reconfigure interface upon networkd failure
Systemd 256 has issue with ndisc that local gateway is messed up, which
causes interface configuration to fail. The fix tries to reconfigure the
interface if that happens.

Also adds a timeout to ensure that we still proceed with doing RS/RA to
avoid regression.

Meanwhile the real underlay issue in systemd is not easy to root cause,
some upstream changes might be related but need time to investigate.

Tested: verified the script logic work, on a failed machine verified
that this can reconfigure the interface with no issue

Change-Id: Ie0acf183b055f2e293d8df8fcee325c083c6df1f
Signed-off-by: Yuxiao Zhang <yuxiaozhang@google.com>

diff --git a/meta-google/recipes-google/networking/gbmc-bridge/gbmc-br-ra.sh.in b/meta-google/recipes-google/networking/gbmc-bridge/gbmc-br-ra.sh.in
--- a/meta-google/recipes-google/networking/gbmc-bridge/gbmc-br-ra.sh.in
+++ b/meta-google/recipes-google/networking/gbmc-bridge/gbmc-br-ra.sh.in
@@ -40,10 +40,21 @@ ROUTE_METRIC=1000
 
 echo "Waiting for ${RA_IF} configuration" >&2
 
-while ! networkctl list "${RA_IF}" | grep -q "configured"; do
+st_check_timeout=60
+st_check_start=$SECONDS
+while (( SECONDS - st_check_start < st_check_timeout )); do
+  if_st=$(networkctl list "${RA_IF}")
+  if [[ "${if_st}" =~ "configured" ]]; then
+    echo "${RA_IF} is configured, doing RA" >&2
+    break;
+  elif [[ "${if_st}" =~ "failed" ]]; then
+    echo "${RA_IF} failed, need reconfiguring" >&2
+    networkctl reload && networkctl reconfigure ${RA_IF}
+  else
+    echo "${RA_IF} still configuring, retry in 2s" >&2
+  fi
   sleep 2
 done
 
-echo "${RA_IF} is configured, doing RA" >&2
 # shellcheck source=meta-google/recipes-google/networking/gbmc-net-common/gbmc-ra.sh
 source /usr/share/gbmc-ra.sh || exit
