Additional traces in event of volume update failure
As documented in openbmc/openbmc#2109, in an automated test, a
ubiupdatevol call failed due to a busy device. However, subsequent
tests, both automated and by hand, were unable to recreate the issue.

In order to better diagnose the issue next time it occurs, this commit
adds additional journal entries in the event of ubiupdatevol failure,
logging information about the current state of any UBI volumes on the
BMC.

Change-Id: Ifa4db46fc873d2177025ec973cace3b23cf17097
Signed-off-by: Michael Tritz <mtritz@us.ibm.com>

diff --git a/meta-openbmc-machines/meta-openpower/common/recipes-phosphor/flash/openpower-software-manager/obmc-flash-bios b/meta-openbmc-machines/meta-openpower/common/recipes-phosphor/flash/openpower-software-manager/obmc-flash-bios
--- a/meta-openbmc-machines/meta-openpower/common/recipes-phosphor/flash/openpower-software-manager/obmc-flash-bios
+++ b/meta-openbmc-machines/meta-openpower/common/recipes-phosphor/flash/openpower-software-manager/obmc-flash-bios
@@ -79,6 +79,11 @@ mount_squashfs() {
     img="/tmp/images/${version}/pnor.xz.squashfs"
     ubiblock --create "/dev/ubi${ubidevid}"
     ubiupdatevol "/dev/ubi${ubidevid}" "${img}"
+    if [ "$?" != 0 ]; then
+      # if this fails, a device is busy - log some info about current volumes
+      df | cat
+      ubinfo -a | cat
+    fi
   fi
 
   if ! is_mounted "${name}"; then
