meta-facebook: yosemite4: Add Power Control Status Check
Implement pre-operation and post-operation status checks for
each power control action.

Change the power cycle behavior to do host on and off on BMC side,
so that each power operation can be checked.

Change-Id: Ib59626ed35965e852bd5ce8c4b776711872bc656
Signed-off-by: Delphine CC Chiu <Delphine_CC_Chiu@wiwynn.com>

diff --git a/meta-facebook/meta-yosemite4/recipes-phosphor/state/phosphor-state-manager/chassis-poweroff b/meta-facebook/meta-yosemite4/recipes-phosphor/state/phosphor-state-manager/chassis-poweroff
--- a/meta-facebook/meta-yosemite4/recipes-phosphor/state/phosphor-state-manager/chassis-poweroff
+++ b/meta-facebook/meta-yosemite4/recipes-phosphor/state/phosphor-state-manager/chassis-poweroff
@@ -3,7 +3,7 @@
 # shellcheck disable=SC2120
 
 # Provide source directive to shellcheck.
-# shellcheck source=meta-facebook/meta-greatlakes/recipes-phosphor/state/phosphor-state-manager/power-cmd
+# shellcheck source=meta-facebook/meta-yosemite4/recipes-phosphor/state/phosphor-state-manager/power-cmd
 source /usr/libexec/phosphor-state-manager/power-cmd
 #IO 0:7 input port for showing slot 1:8 power status
 #IO 8:16 output port for controlling slot 1:8 power status
@@ -42,7 +42,11 @@ chassis-power-off()
         fi
 }
 
-chassis_status=$(gpioget "$GPIOCHIP_IO_EXP_SLOT_PWR_CTRL" "$IO_EXP_SLOT_PWR_STATUS")
+if ! chassis_status=$(gpioget "$GPIOCHIP_IO_EXP_SLOT_PWR_CTRL" "$IO_EXP_SLOT_PWR_STATUS"); then
+    echo "Failed to get chassis status"
+    exit 1
+fi
+
 if [ "$chassis_status" == "$STATE_ON" ]
 then
         chassis-power-off
diff --git a/meta-facebook/meta-yosemite4/recipes-phosphor/state/phosphor-state-manager/chassis-poweron b/meta-facebook/meta-yosemite4/recipes-phosphor/state/phosphor-state-manager/chassis-poweron
--- a/meta-facebook/meta-yosemite4/recipes-phosphor/state/phosphor-state-manager/chassis-poweron
+++ b/meta-facebook/meta-yosemite4/recipes-phosphor/state/phosphor-state-manager/chassis-poweron
@@ -3,7 +3,7 @@
 # shellcheck disable=SC2120
 
 # Provide source directive to shellcheck.
-# shellcheck source=meta-facebook/meta-greatlakes/recipes-phosphor/state/phosphor-state-manager/power-cmd
+# shellcheck source=meta-facebook/meta-yosemite4/recipes-phosphor/state/phosphor-state-manager/power-cmd
 source /usr/libexec/phosphor-state-manager/power-cmd
 
 GPIOCHIP_IO_EXP_SLOT_PWR_CTRL=$(basename "/sys/bus/i2c/devices/$SPIDER_BOARD_IO_EXP_BUS_NUM-00$IO_EXP_SLOT_PWR_CTRL_ADDR/"*gpiochip*)
@@ -36,7 +36,11 @@ chassis-power-on()
     fi
 }
 
-chassis_status=$(gpioget "$GPIOCHIP_IO_EXP_SLOT_PWR_CTRL" "$IO_EXP_SLOT_PWR_STATUS")
+if ! chassis_status=$(gpioget "$GPIOCHIP_IO_EXP_SLOT_PWR_CTRL" "$IO_EXP_SLOT_PWR_STATUS"); then
+    echo "Failed to get chassis status"
+    exit 1
+fi
+
 if [ "$chassis_status" == "$STATE_OFF" ]
 then
     chassis-power-on
diff --git a/meta-facebook/meta-yosemite4/recipes-phosphor/state/phosphor-state-manager/host-powercycle b/meta-facebook/meta-yosemite4/recipes-phosphor/state/phosphor-state-manager/host-powercycle
--- a/meta-facebook/meta-yosemite4/recipes-phosphor/state/phosphor-state-manager/host-powercycle
+++ b/meta-facebook/meta-yosemite4/recipes-phosphor/state/phosphor-state-manager/host-powercycle
@@ -3,15 +3,55 @@
 # shellcheck disable=SC2120
 
 # Provide source directive to shellcheck.
-# shellcheck source=meta-facebook/meta-greatlakes/recipes-phosphor/state/phosphor-state-manager/power-cmd
+# shellcheck source=meta-facebook/meta-yosemite4/recipes-phosphor/state/phosphor-state-manager/power-cmd
 source /usr/libexec/phosphor-state-manager/power-cmd
+CHASSIS_ID=$1
 
-# TODO: check power status before do power cycle
-# Set state effecter state: Entity ID 0x0000 for host power control, 0x3 for power cycle
-EID=$(($1*10))
-if ! pldmtool raw -d 0x80 0x02 0x39 0x00 0x00 0x01 0x00 0x03 -m "$EID"
-then
-    echo "Failed to set host$1 power cycle"
-else
-    echo "Host is power cycle"
+CHASSIS_BUS=$((CHASSIS_ID - 1))
+IO_EXP_P0_PWRGD_R_OUT=18
+GPIOCHIP_IO_EXP_HOST_POWER_STATUS=$(basename "/sys/bus/i2c/devices/$CHASSIS_BUS-0023/"*gpiochip*)
+
+EID=$((CHASSIS_ID * 10))
+
+get_host_status() {
+    if ! host_status=$(gpioget "$GPIOCHIP_IO_EXP_HOST_POWER_STATUS" "$IO_EXP_P0_PWRGD_R_OUT"); then
+        echo "Failed to get host status"
+        exit 1
+    fi
+}
+
+# Get initial host status
+get_host_status
+
+# Current power is ON, cycle do OFF to ON. If current power is OFF then do ON
+if [ "$host_status" == "$STATE_ON" ]; then
+    # Set state effecter state: Entity ID 0x0000 for host power control, 0x2 for power off
+    pldmtool raw -d 0x80 0x02 0x39 0x00 0x00 0x01 0x00 0x02 -m "$EID"
+    # Wait for the host to power off
+    sleep 10s
+
+    # Get host status again after attempting to power off
+    get_host_status
+
+    if [ "$host_status" != "$STATE_OFF" ]; then
+        echo "Do power cycle fail, fail to set host$CHASSIS_ID power off"
+        exit 1
+    fi
 fi
+
+if [ "$host_status" != "$STATE_ON" ]; then
+    # Set state effecter state: Entity ID 0x0000 for host power control, 0x1 for power on
+    pldmtool raw -d 0x80 0x02 0x39 0x00 0x00 0x01 0x00 0x01 -m "$EID"
+    sleep 2s
+
+    # Get host status again after attempting to power on
+    get_host_status
+
+    if [ "$host_status" != "$STATE_ON" ]; then
+        echo "Do power cycle, failed to set host$CHASSIS_ID power on"
+        exit 1
+    fi
+fi
+
+echo "Host power cycle success"
+exit 0;
diff --git a/meta-facebook/meta-yosemite4/recipes-phosphor/state/phosphor-state-manager/host-poweroff b/meta-facebook/meta-yosemite4/recipes-phosphor/state/phosphor-state-manager/host-poweroff
--- a/meta-facebook/meta-yosemite4/recipes-phosphor/state/phosphor-state-manager/host-poweroff
+++ b/meta-facebook/meta-yosemite4/recipes-phosphor/state/phosphor-state-manager/host-poweroff
@@ -3,15 +3,49 @@
 # shellcheck disable=SC2120
 
 # Provide source directive to shellcheck.
-# shellcheck source=meta-facebook/meta-greatlakes/recipes-phosphor/state/phosphor-state-manager/power-cmd
+# shellcheck source=meta-facebook/meta-yosemite4/recipes-phosphor/state/phosphor-state-manager/power-cmd
 source /usr/libexec/phosphor-state-manager/power-cmd
 
-# TODO: check power status before do power off
+CHASSIS_BUS=$(($1 - 1))
+IO_EXP_P0_PWRGD_R_OUT=18
+GPIOCHIP_IO_EXP_HOST_POWER_STATUS=$(basename "/sys/bus/i2c/devices/$CHASSIS_BUS-0023/"*gpiochip*)
+
+get_host_status() {
+    if ! host_status=$(gpioget "$GPIOCHIP_IO_EXP_HOST_POWER_STATUS" "$IO_EXP_P0_PWRGD_R_OUT"); then
+        echo "Failed to get host status"
+        exit 1
+    fi
+}
+
+get_host_status
+
+if [ "$host_status" == "$STATE_OFF" ]
+then
+    echo "Already host power off."
+    exit 0;
+fi
+
 # Set state effecter state: Entity ID 0x0000 for host power control, 0x2 for power off
 EID=$(($1*10))
-if ! pldmtool raw -d 0x80 0x02 0x39 0x00 0x00 0x01 0x00 0x02 -m "$EID"
+pldmtool raw -d 0x80 0x02 0x39 0x00 0x00 0x01 0x00 0x02 -m "$EID"
+
+# Host power off will trigger the BIC to configure the server board CPLD register and set the power sequence.
+# Power Sequence:
+#   - Set PLAT_PLDM_HOST_PWR_CTRL_DEFAULT to 0xFF
+#   - Set PLAT_PLDM_HOST_PWR_BTN_LOW to 0xFE
+#   - Sleep for 6 seconds
+#   - Set PLAT_PLDM_HOST_PWR_CTRL_DEFAULT back to 0xFF
+
+# Wait for the host to power off
+sleep 10s
+
+get_host_status
+
+if [ "$host_status" == "$STATE_OFF" ]
 then
-    echo "Failed to set host$1 power off"
+    echo "Host power off success"
+    exit 0;
 else
-    echo "Host is power off"
+    echo "Failed to set host$1 power off"
+    exit 1
 fi
diff --git a/meta-facebook/meta-yosemite4/recipes-phosphor/state/phosphor-state-manager/host-poweron b/meta-facebook/meta-yosemite4/recipes-phosphor/state/phosphor-state-manager/host-poweron
--- a/meta-facebook/meta-yosemite4/recipes-phosphor/state/phosphor-state-manager/host-poweron
+++ b/meta-facebook/meta-yosemite4/recipes-phosphor/state/phosphor-state-manager/host-poweron
@@ -1,18 +1,53 @@
 #!/bin/bash
 
 # Provide source directive to shellcheck.
-# shellcheck source=meta-facebook/meta-greatlakes/recipes-phosphor/state/phosphor-state-manager/power-cmd
-CHASSIS_ID=$1
+# shellcheck source=meta-facebook/meta-yosemite4/recipes-phosphor/state/phosphor-state-manager/power-cmd
 source /usr/libexec/phosphor-state-manager/power-cmd
+CHASSIS_ID=$1
 
-# TODO: check power status before do power on
-# Set state effecter state: Entity ID 0x0000 for host power control, 0x1 for power on
+CHASSIS_BUS=$(($1 - 1))
+IO_EXP_P0_PWRGD_R_OUT=18
+GPIOCHIP_IO_EXP_HOST_POWER_STATUS=$(basename "/sys/bus/i2c/devices/$CHASSIS_BUS-0023/"*gpiochip*)
+
+get_host_status() {
+    if ! host_status=$(gpioget "$GPIOCHIP_IO_EXP_HOST_POWER_STATUS" "$IO_EXP_P0_PWRGD_R_OUT"); then
+        echo "Failed to get host status"
+        exit 1
+    fi
+}
+
+get_host_status
+
+if [ "$host_status" == "$STATE_ON" ]
+then
+    echo "Already host power on."
+    exit 0;
+fi
+
+# Need to ensure that the mctp connection is complete so that pldmtool can set up successfully.
 /usr/libexec/phosphor-state-manager/wait-until-mctp-connection-done "$CHASSIS_ID"
 
+# Set state effecter state: Entity ID 0x0000 for host power control, 0x1 for power on
 EID=$(($1*10))
-if ! pldmtool raw -d 0x80 0x02 0x39 0x00 0x00 0x01 0x00 0x01 -m "$EID"
+pldmtool raw -d 0x80 0x02 0x39 0x00 0x00 0x01 0x00 0x01 -m "$EID"
+
+# Host power ON will trigger the BIC to configure the server board CPLD register and set the power sequence.
+# Power Sequence:
+#   - Set PLAT_PLDM_HOST_PWR_CTRL_DEFAULT to 0xFF
+#   - Set PLAT_PLDM_HOST_PWR_BTN_LOW to 0xFE
+#   - Sleep for 1 second
+#   - Set PLAT_PLDM_HOST_PWR_CTRL_DEFAULT back to 0xFF
+
+# Wait for the host to power on
+sleep 2s
+
+get_host_status
+
+if [ "$host_status" == "$STATE_ON" ]
 then
-    echo "Failed to set host$1 power on"
+    echo "Host power on success"
+    exit 0;
 else
-    echo "Host is power on"
+    echo "Failed to set host$1 power on"
+    exit 1
 fi
