phosphor-static-norootfs-init: Add script that remounts /run/mnt-persist as read-only
Platforms could use this common script when hard power-cycling.
Remounting the filesystem as read-only helps in avoiding possible data corruption.

Test Plan:

- Add logic around using this script inside yosemite4.
- In yosemite4 a sled cycle is hard powercycle of the whole platform.
- See the filesystem being remounted as read-only when calling sled-cycle

...
Execute sled cycle
o "/xyz/openbmc_project/logging/entry/120914"
Starting sled cycle...
Attempting to remount /run/mnt-persist as read-only with a number of 3 retries
Succeeded to remount /run/mnt-persist as read-only
...

Change-Id: I6dc837e0441f3cdb1345ba84856bc64ea5205a13
Signed-off-by: Robert Ercean Dima <robert3@meta.com>
Signed-off-by: Patrick Williams <patrick@stwcx.xyz>

diff --git a/meta-facebook/meta-yosemite4/recipes-phosphor/state/phosphor-state-manager/chassis-powercycle b/meta-facebook/meta-yosemite4/recipes-phosphor/state/phosphor-state-manager/chassis-powercycle
--- a/meta-facebook/meta-yosemite4/recipes-phosphor/state/phosphor-state-manager/chassis-powercycle
+++ b/meta-facebook/meta-yosemite4/recipes-phosphor/state/phosphor-state-manager/chassis-powercycle
@@ -207,6 +207,16 @@ chassis-power-cycle()
 
 sled-cycle()
 {
+    # Remount file system as read-only before doing sled cycle
+    if ! /usr/libexec/phosphor-static-norootfs-init/remount-filesystem-readonly; then
+        msg="Failed to remount /run/mnt-persist as read-only"
+        echo "${msg}"
+        add_sel "${msg}" "Error"
+    else
+        # If the remount is succesful, add_sel will fail so we can't log this
+        echo "Succeeded to remount /run/mnt-persist as read-only"
+    fi
+
     if [ -z "$MANAGEMENT_BOARD_VERSION" ]; then
         set_gpio FM_BMC_SLED_CYCLE_R 1
     elif [ "$MANAGEMENT_BOARD_VERSION" = "DVT" ] || [ "$MANAGEMENT_BOARD_VERSION" = "EVT" ]; then
