meta-facebook: yosemite4: Support sled power cycle
Description:
- Support sled power cycle
- Revise 12v power control and host power control

Design:
- Add sled power cycle action as chassis 0 by setting virtual i/o exp output port.
- Revise gpio setting and command parameter for 12v power control and host power control.

Test Case:
- Set sled cycle by phosphor-state-manager: pass
- Set 12V on/off/cycle by phosphor-state-manager: pass
- Set host on/off/cycle/reset by phosphor-state-manager: pass

Test Log:
root@yosemite4:~# busctl set-property xyz.openbmc_project.State.Chassis0 /xyz/openbmc_project/state/chassis0 xyz.openbmc_project.State.Chassis RequestedPowerTransition s "xyz.openbmc_project.State.Chassis.Transition.PowerCycle"
root@yosemite4:~# journalctl --since "20 second ago"
Jul 28 07:03:44 yosemite4 phosphor-chassis-state-manager[349]: Change to Chassis Requested Power State: xyz.openbmc_project.State.Chassis.Transition.PowerCycle
Jul 28 07:03:44 yosemite4 systemd[1]: Created slice Slice /system/chassis-powercycle.
Jul 28 07:03:44 yosemite4 systemd[1]: Starting Chassis Power Cycle: 0...
Jul 28 07:03:45 yosemite4 chassis-powercycle[661]: Starting sled cycle...

Change-Id: I6cdb26a2fd8d4d445ca41302d070a369a40c79dd
Signed-off-by: Delphine CC Chiu <Delphine_CC_Chiu@wiwynn.com>

diff --git a/meta-facebook/meta-yosemite4/recipes-phosphor/state/phosphor-state-manager/chassis-powercycle b/meta-facebook/meta-yosemite4/recipes-phosphor/state/phosphor-state-manager/chassis-powercycle
--- a/meta-facebook/meta-yosemite4/recipes-phosphor/state/phosphor-state-manager/chassis-powercycle
+++ b/meta-facebook/meta-yosemite4/recipes-phosphor/state/phosphor-state-manager/chassis-powercycle
@@ -6,13 +6,15 @@
 # shellcheck source=meta-facebook/recipes-phosphor/state/phosphor-state-manager/greatlakes/power-cmd
 source /usr/libexec/phosphor-state-manager/power-cmd
 
-GPIOCHIP_IO_EXP_SLOT_PWR_CTRL=$(basename "/sys/bus/i2c/devices/$MEDUSA_IO_EXP_BUS_NUM-00$IO_EXP_SLOT_PWR_CTRL_ADDR/"*gpiochip*)
+GPIOCHIP_IO_EXP_SLOT_PWR_CTRL=$(basename "/sys/bus/i2c/devices/$SPIDER_BOARD_IO_EXP_BUS_NUM-00$IO_EXP_SLOT_PWR_CTRL_ADDR/"*gpiochip*)
+GPIOCHIP_IO_EXP_SLED_PWR_CTRL=$(basename "/sys/bus/i2c/devices/$MANAGEMENT_BOARD_IO_EXP_BUS_NUM-00$IO_EXP_SLED_PWR_CTRL_ADDR/"*gpiochip*)
 
 #IO 0:7 input port for showing slot 1:8 power status
 #IO 8:16 output port for controlling slot 1:8 power status
 CHASSIS_ID=$1
 IO_EXP_SLOT_PWR_STATUS=$((CHASSIS_ID - 1))
 IO_EXP_SLOT_PWR_CTRL=$((IO_EXP_SLOT_PWR_STATUS + 8))
+IO_EXP_SLED_CYCLE=12
 
 chassis-power-cycle()
 {
@@ -23,13 +25,13 @@ chassis-power-cycle()
         chassis_status=$(gpioget "$GPIOCHIP_IO_EXP_SLOT_PWR_CTRL" "$IO_EXP_SLOT_PWR_STATUS")
         if [ "$chassis_status" == "$STATE_ON" ]
         then
-            if ! gpioset "$GPIOCHIP_IO_EXP_SLOT_PWR_CTRL" "$IO_EXP_SLOT_PWR_CTRL"=0
+            if ! gpioset "$GPIOCHIP_IO_EXP_SLOT_PWR_CTRL" "$IO_EXP_SLOT_PWR_CTRL"=1
             then
                 echo "Failed to set slot$1 power off"
             fi
             sleep 10
         fi
-        if ! gpioset "$GPIOCHIP_IO_EXP_SLOT_PWR_CTRL" "$IO_EXP_SLOT_PWR_CTRL"=1
+        if ! gpioset "$GPIOCHIP_IO_EXP_SLOT_PWR_CTRL" "$IO_EXP_SLOT_PWR_CTRL"=0
         then
             echo "Failed to set slot$1 power on"
         fi
@@ -53,8 +55,11 @@ chassis-power-cycle()
 
 if [ "$1" == 0 ]
 then
-    # TODO: SLED cycle
-    echo "SLED-cycle is not support for now"
+    echo "Starting sled cycle..."
+    if ! gpioset "$GPIOCHIP_IO_EXP_SLED_PWR_CTRL" "$IO_EXP_SLED_CYCLE"=1
+    then
+        echo "Failed to do sled cycle"
+    fi
 else
     echo "Starting slot$1 cycle"
     chassis-power-cycle "$1"
