meta-facebook: harma: Add logging for prochot event
Change-Id: I83574bcc2e2cc94ec552b1734bd41441cf1ff2d0
Signed-off-by: Prabha Veerubhotla <vvlprabha@gmail.com>

diff --git a/meta-facebook/meta-harma/recipes-phosphor/gpio/phosphor-gpio-monitor/thermal-event-logger b/meta-facebook/meta-harma/recipes-phosphor/gpio/phosphor-gpio-monitor/thermal-event-logger
--- a/meta-facebook/meta-harma/recipes-phosphor/gpio/phosphor-gpio-monitor/thermal-event-logger
+++ b/meta-facebook/meta-harma/recipes-phosphor/gpio/phosphor-gpio-monitor/thermal-event-logger
@@ -4,53 +4,74 @@
 source /usr/libexec/phosphor-gpio-monitor/logging-util
 
 HELP="
-Usage: thermal-event-logger <event> <id_gpio-name>
-<event> is the thermal event to log,
-e.g. DeviceOverOperatingTemperatureFault / DeviceOperatingNormalTemperature.
+Usage: thermal-event-logger <type> <gpio name>
+<event> is the event type,
+e.g. assert/deassert.
 
-<id_gpio-name> is defined in json file,
-e.g. 2_cpu0-thermtrip-alert.service
+<gpio-name> is defined in json file,
+e.g. cpu0-thermtrip-alert
 "
 
-# get assert or deassert message
-if [ "$1" == "DeviceOverOperatingTemperatureFault" ]; then
-  action="assert"
-elif [ "$1" == "DeviceOperatingNormalTemperature" ]; then
-  action="deassert"
+# check if parameters are missing
+if [[ -z "$1" || -z "$2" ]]; then
+    echo "Missing required arguments: event type, gpio name."
+    echo "$HELP"
+    exit 1
 fi
 
-MESSAGE=$2
-# get gpio chip ID
-number="${MESSAGE%%_*}"
+# get some parameters
+GPIO_NAME=$2
+case $1-$2 in
+    assert-cpu0-thermtrip-alert)
+    MSG_ID="xyz.openbmc_project.State.Thermal.DeviceOverOperatingTemperatureFault"
+    ;;
+    deassert-cpu0-thermtrip-alert | assert-cpu0-prochot-alert)
+    MSG_ID="xyz.openbmc_project.State.Thermal.DeviceOverOperatingTemperature"
+    ;;
+    deassert-cpu0-prochot-alert)
+    MSG_ID="xyz.openbmc_project.State.Thermal.DeviceOperatingNormalTemperature"
+    ;;
+    *)
+    echo "Unrecognized event type or gpio name."
+    exit 1
+esac
 
-# remove prefix from 0_xxxxxx to xxxxxx
-GPIO_NAME="${MESSAGE#*_}"
-MSG_ID="xyz.openbmc_project.State.Thermal.$1"
 DEVICE_PATH="/xyz/openbmc_project/State/Thermal/cpu0"
 STASH_FILE="/run/${GPIO_NAME}.log_entry"
 
-if gpio_logging_valid "$number" "$action" ; then
-    case $1 in
-        "-h")
-            echo "$HELP"
-            ;;
-
-        "DeviceOverOperatingTemperatureFault")
+if check_valid_sgpio; then
+    # This delay ensures the BMC does not receive abnormal events
+    # during CMM/MB AC cycling or tray unplugging.
+    # Such actions can cause the CPLD to lose power before the BMC,
+    # leading to abnormal events being received.
+    sleep 2
+    case $1-$2 in
+        assert-*)
             if [ ! -s "$STASH_FILE" ]; then
-                 /usr/bin/log-create "$MSG_ID" --json \
-                     "{ \"DEVICE\": \"${DEVICE_PATH}\", \"FAILURE_DATA\": \"${GPIO_NAME}\"}" \
-                     > "${STASH_FILE}"
+                    /usr/bin/log-create "$MSG_ID" --json \
+                        "{ \"DEVICE\": \"${DEVICE_PATH}\", \"FAILURE_DATA\": \"${GPIO_NAME}\"}" \
+                        > "${STASH_FILE}"
             fi
             ;;
 
-        "DeviceOperatingNormalTemperature")
+        deassert-cpu0-thermtrip-alert)
+            if [ -e "${STASH_FILE}" ]; then
+                    log-resolve -p "$(< "${STASH_FILE}")" && rm "${STASH_FILE}"
+            fi
+            ;;
+
+        deassert-cpu0-prochot-alert)
             if [ -e "${STASH_FILE}" ]; then
                 log-resolve -p "$(< "${STASH_FILE}")" && rm "${STASH_FILE}"
             fi
             /usr/bin/log-create "$MSG_ID" --json \
-                "{ \"DEVICE\": \"${DEVICE_PATH}\", \"FAILURE_DATA\": \"${GPIO_NAME}\"}"
+                "{ \"DEVICE\": \"${DEVICE_PATH}\"}"
             ;;
+        *)
+            echo "Unrecognized thermal event."
+            exit 1
     esac
+else
+    echo "Invalid sgpio."
 fi
-
 exit 0
