meta-facebook: catalina: Update RMC main power check method
The CPLD register mapping is subject to change over time during
development. This poses a potential risk of unexpected host power on/off
if the BMC relies on an incorrect register bit for RMC power status
checking.

To avoid this risk, update the power check mechanism to use IO Expander,
aligning with phosphor-gpio-monitor. Since phosphor-gpio-monitor
occupies the GPIO pin resource, we use an I2C command to read the input
port register value for RMC power status verification instead.

Change-Id: Ic27f5496d31c4e5e57640c4bea06aab41b68dfc0
Signed-off-by: Potin Lai <potin.lai@quantatw.com>

diff --git a/meta-facebook/meta-catalina/recipes-phosphor/state/phosphor-state-manager/power-cmd b/meta-facebook/meta-catalina/recipes-phosphor/state/phosphor-state-manager/power-cmd
--- a/meta-facebook/meta-catalina/recipes-phosphor/state/phosphor-state-manager/power-cmd
+++ b/meta-facebook/meta-catalina/recipes-phosphor/state/phosphor-state-manager/power-cmd
@@ -63,17 +63,17 @@ is_rmc_main_power_disable()
         return 1
     fi
 
-    if ! reg_val="$(i2ctransfer -y -f 14 w1@0x1e 0x0d r1)"; then
-        # failed to get rmc main power state from cpld register
+    if ! reg_val="$(i2ctransfer -y -f 14 w1@0x12 0x01 r1)"; then
+        # failed to get rmc main power state from cpld ioexp
         # assume rmc main power is enabled
-        echo "[DEBUG] failed to get rmc main power state from cpld register"
+        echo "[DEBUG] failed to get rmc main power state from cpld ioexp"
         return 1
     fi
 
-    # check bit[3]
-    # 1: rmc main power disabled
-    # 0: rmc main power enabled
-    if (( (reg_val & 0x08) == 0 )); then
+    # check bit[1]
+    # 0: rmc main power disabled
+    # 1: rmc main power enabled
+    if (( (reg_val & 0x02) == 0x02 )); then
         echo "[DEBUG] rmc main power is enabled"
         return 1
     fi
