meta-facebook: catalina: Set fan PWM to 80% at system initial
Set all fan PWMs to 80% during system initialization, before the
phosphor-pid-control service starts, as the default duty cycle to align
with thermal team requirements.

Change-Id: I7dec22a5f68490ff70ba49a97775e96eb83d9c3f
Signed-off-by: Potin Lai <potin.lai@quantatw.com>

diff --git a/meta-facebook/meta-catalina/recipes-catalina/plat-svc/files/catalina/platform-early-sys-init b/meta-facebook/meta-catalina/recipes-catalina/plat-svc/files/catalina/platform-early-sys-init
--- a/meta-facebook/meta-catalina/recipes-catalina/plat-svc/files/catalina/platform-early-sys-init
+++ b/meta-facebook/meta-catalina/recipes-catalina/plat-svc/files/catalina/platform-early-sys-init
@@ -45,6 +45,17 @@ config_fan()
         echo "Configure MAX31790 fan controller"
         config_fan_max31790
     fi
+
+    # Set all fan pwm to 80%
+    pwm_value=204
+    for pwm_node in /sys/bus/i2c/devices/*/hwmon/*/pwm*
+    do
+        if [[ ! "$pwm_node" =~ _enable ]]; then
+            if ! echo $pwm_value > "$pwm_node"; then
+                echo "Set $pwm_node: failed"
+            fi
+        fi
+    done
 }
 
 config_ltc4287_hsc()
